[workspace.package]
edition = "2021"
authors = ["Andrew Ward (andy.ward.uk@gmail.com)"]

[workspace]
members = ["cards", "solver", "solve", "solve_all", "stats"]
resolver = "2"

[profile.release]
lto = true
